## Seminar 1 (Week 1)

In [ ]:
#Q1 I. Create a list of Australian States

Australian_States = ["New South Wales", "Victoria", "Queensland", "Western Australia", "South Australia", "Tasmania"]
print(Australian_States)

['New South Wales', 'Victoria', 'Queensland', 'Western Australia', 'South Australia', 'Tasmania']


In [ ]:
#Q1 II. Create a list of tuples with numbers and it's square value. 

input_list = [5, 8, 16, 23, 54, 67, 89]
input_squares = [(x, x**2) for x in input_list]
print(input_squares)

[(5, 25), (8, 64), (16, 256), (23, 529), (54, 2916), (67, 4489), (89, 7921)]


In [6]:
#Q1 III. Create a Tuple and determine it's length

tuple_1 = (1, 9, 25, 'a', 'b')
print(len(tuple_1))

5


In [ ]:
 #Q1 IV. Create a Disctonary for Students final grades
 
student_grades = {'james':45, 'mary': 92, 'john': 78, 'linda': 90}
for name in student_grades:
    print(name, student_grades[name])

james 45
mary 92
john 78
linda 90


In [7]:
#Q1 V. Create a function to calculate factorial of a number

def function_factorial(x):
    y = 1
    for i in range(1, x + 1):
        y = y * i
    return y

# To Calculate a factorial of x, input your number in () below 
function_factorial(10)

3628800

In [ ]:
#Q2 I. Create a identity 5x5 matrix

import numpy as np

matrix_5x5 = np.eye(5)
print(matrix_5x5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
#Q2 II. Create a 12x12 matrix with the border values as 1 and inside values as 0

matrix_12x12 = np.ones((12,12))
matrix_12x12[1:11, 1:11] = 0
print(matrix_12x12)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [35]:

  #Q2 III. Mutiple two matrix of the same size

  
  num1 = np.array([[10,20,30], [4,8,9]])
  print(num1)
  
   

TypeError: 'tuple' object is not callable