## Seminar 1 (Week 1)

In [ ]:
#Q1 I. Create a list of Australian States

Australian_States = ["New South Wales", "Victoria", "Queensland", "Western Australia", "South Australia", "Tasmania"]
print(Australian_States)

['New South Wales', 'Victoria', 'Queensland', 'Western Australia', 'South Australia', 'Tasmania']


In [ ]:
#Q1 II. Create a list of tuples with numbers and it's square value. 

input_list = [5, 8, 16, 23, 54, 67, 89]
input_squares = [(x, x**2) for x in input_list]
print(input_squares)

[(5, 25), (8, 64), (16, 256), (23, 529), (54, 2916), (67, 4489), (89, 7921)]


In [6]:
#Q1 III. Create a Tuple and determine it's length

tuple_1 = (1, 9, 25, 'a', 'b')
print(len(tuple_1))

5


In [ ]:
 #Q1 IV. Create a Disctonary for Students final grades
 
student_grades = {'james':45, 'mary': 92, 'john': 78, 'linda': 90}
for name in student_grades:
    print(name, student_grades[name])

james 45
mary 92
john 78
linda 90


In [7]:
#Q1 V. Create a function to calculate factorial of a number

def function_factorial(x):
    y = 1
    for i in range(1, x + 1):
        y = y * i
    return y

# To Calculate a factorial of x, input your number in () below 
function_factorial(10)

3628800

In [1]:
#Q2 I. Create a identity 5x5 matrix

import numpy as np

matrix_5x5 = np.eye(5)
print(matrix_5x5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
#Q2 II. Create a 12x12 matrix with the border values as 1 and inside values as 0

matrix_12x12 = np.ones((12,12))
matrix_12x12[1:11, 1:11] = 0
print(matrix_12x12)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [22]:

  #Q2 III. Mutiple two matrix of the same size

  num1 = np.array([[10,20,30], [4,8,9]])
  num2 = np.array([[14,26,3], [2,3,10]])
  num3 = np.multiply(num1, num2)  
  
  print("Matrix 1")
  print(num1)
  print("Matrix 2")
  print(num2)
  print("Mutiple Matrix Result")
  print(num3)
   

Matrix 1
[[10 20 30]
 [ 4  8  9]]
Matrix 2
[[14 26  3]
 [ 2  3 10]]
Mutiple Matrix Result
[[140 520  90]
 [  8  24  90]]


In [27]:
#Q3 I. Create a .pd dataframe for students grades

import pandas as pd

student_grades = pd.DataFrame(
    {
        "Bob": [80, 97, 85, 67, 80],
        "Alice": [82, 67, 85, 62, 80],
        "John": [89, 90, 85, 77, 80],
    }
)
student_grades

Bob  Alice  John
0   80     82    89
1   97     67    90
2   85     85    85
3   67     62    77
4   80     80    80

In [30]:
#Q3 II. Print the first 2 rows of the dataframe

student_grades.head(2)

Bob  Alice  John
0   80     82    89
1   97     67    90

In [38]:
#Q3 III. Import dict into pandas dataframe

exam_data = {
    'name': ['Alice', 'Dee', 'Kathy', 'Homes', 'Boris', 'Hanson', 'Bourne', 
            'Matt', 'Jason', 'Jarvis'], 
    'score': [115, 7, 15.5, np.nan, 9, 19, 15.5, np.nan, 8.5, 19.5], 
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
} 
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

student_data = pd.DataFrame(exam_data, index=labels)
student_data

name  score  attempts qualify
a   Alice  115.0         1     yes
b     Dee    7.0         3      no
c   Kathy   15.5         2     yes
d   Homes    NaN         3      no
e   Boris    9.0         2      no
f  Hanson   19.0         3     yes
g  Bourne   15.5         1     yes
h    Matt    NaN         1      no
i   Jason    8.5         2      no
j  Jarvis   19.5         1     yes

In [43]:
#Q3 III. a) Change Dee to Eve

student_data['name'] = student_data['name'].replace('Dee', 'Eve')
student_data

name  score  attempts qualify
a   Alice  115.0         1     yes
b     Eve    7.0         3      no
c   Kathy   15.5         2     yes
d   Homes    NaN         3      no
e   Boris    9.0         2      no
f  Hanson   19.0         3     yes
g  Bourne   15.5         1     yes
h    Matt    NaN         1      no
i   Jason    8.5         2      no
j  Jarvis   19.5         1     yes

In [46]:
#Q3 III. b) Find rows with missing values

student_data[(student_data.isna().any(axis=1))]

name  score  attempts qualify
d  Homes    NaN         3      no
h   Matt    NaN         1      no

In [48]:
#Q3 III. c) Show rows where the number of attempts is less than 2 and score greater than 15

student_data[(student_data['attempts'] < 2) & (student_data['score'] > 15)]

name  score  attempts qualify
a   Alice  115.0         1     yes
g  Bourne   15.5         1     yes
j  Jarvis   19.5         1     yes

In [ ]:
#Q3 III. d) Replace NaN with 10

student_data.fillna(value=10)

name  score  attempts qualify
a   Alice  115.0         1     yes
b     Eve    7.0         3      no
c   Kathy   15.5         2     yes
d   Homes   10.0         3      no
e   Boris    9.0         2      no
f  Hanson   19.0         3     yes
g  Bourne   15.5         1     yes
h    Matt   10.0         1      no
i   Jason    8.5         2      no
j  Jarvis   19.5         1     yes