In [7]:
from sklearn import svm
from sklearn import datasets
# Load dataset
iris = datasets.load_iris()
clf = svm.LinearSVC()
# learn from the data
clf.fit(iris.data, iris.target)
# predict for unseen data
clf.predict([[ 5.0,  3.6,  1.3,  0.25]])
# Parameters of model can be changed by using the attributes ending with an underscore
print(clf.coef_ )

[[ 0.18344977  0.4549369  -0.81495365 -0.43357339]
 [ 0.05524625 -0.9008946   0.40923385 -0.9606271 ]
 [-0.85048831 -0.98657611  1.38090768  1.86511359]]


In [10]:
#import the model
from sklearn import linear_model
reg = linear_model.LinearRegression()
# use it to fit a data
reg.fit ([[0, 0], [1, 1], [2, 2]], [0, 1, 2])
# Let's look into the fitted data
print(reg.coef_)

[0.5 0.5]


In [13]:
from sklearn import datasets
# Load dataset
iris = datasets.load_iris()
# Create and fit a nearest-neighbor classifier
from sklearn import neighbors
knn = neighbors.KNeighborsClassifier()
knn.fit(iris.data, iris.target)
# Predict and print the result
result=knn.predict([[0.1, 0.2, 0.3, 0.4]])
print(result)

[0]


In [15]:
from sklearn import cluster, datasets
# load data
iris = datasets.load_iris()
# create clusters for k=3
k=3
k_means = cluster.KMeans(k)
# fit data
k_means.fit(iris.data)
# print results
print( k_means.labels_[::10])
print( iris.target[::10])

[1 1 1 1 1 0 2 2 2 2 0 0 0 0 0]
[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]


In [18]:
from sklearn.linear_model import SGDClassifier
import numpy as np

# Initialize a Stochastic Gradient Descent (SGD) Classifier model
model = SGDClassifier()

# Loop through 10 batches of data
for batch in range(10):
    # Generate a batch of random features (X_batch) with shape (1000, 20)
    X_batch = np.random.rand(1000, 20)
    # Generate a batch of random target values (y_batch) with shape (1000,) containing either 0 or 1
    y_batch = np.random.randint(0, 2, 1000)
    # Use the partial_fit method to train the model on the current batch of data
    # This method is particularly useful for large datasets that cannot fit into memory at once
    # The 'classes' parameter is specified to ensure the model is aware of the classes it's training on
    model.partial_fit(X_batch, y_batch, classes=[0, 1])

In [21]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing


{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': 